# Generated by Django 5.2.6 on 2025-11-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0003_remove_order_items_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cart_items",
            field=models.ManyToManyField(
                related_name="orders", to="restaurants.cartitem"
            ),
        ),
    ]
