# Generated by Django 5.2.9 on 2026-01-19 06:09

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0005_alter_dish_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="name",
            field=models.CharField(
                max_length=40,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Допустимы только русские и английские буквы, максимум 40 символов",
                        regex="^[A-Za-zА-Яа-яЁё\\s]{1,40}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="name",
            field=models.CharField(
                max_length=40,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Допустимы только русские и английские буквы, максимум 40 символов",
                        regex="^[A-Za-zА-Яа-яЁё\\s]{1,40}$",
                    )
                ],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("user", "dish")},
        ),
        migrations.AlterUniqueTogether(
            name="dish",
            unique_together={("restaurant", "name")},
        ),
    ]
