@host = http://127.0.0.1:8000
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzMTkwNjExLCJpYXQiOjE3NjMxOTAzMTEsImp0aSI6IjVmYjlkZDM2Yjg3MzQ4ZjNhMGZiOGM3MmI3MzlkZTFkIiwidXNlcl9pZCI6IjIifQ.7dQ-TKYhkp757429Ycw1KF0h70NPn69FuhzzHc7fhTY
POST http://127.0.0.1:8000/api/auth/register/
Content-Type: application/json

{
  "username": "testuser",
  "email": "test@example.com",
  "password": "password123"
}

### 2. Авторизация пользователя
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123"
}

### 3. Список ресторанов
GET http://127.0.0.1:8000/api/restaurants/
Authorization: Bearer {{token}}

### 4. Ресторан по ID
GET http://127.0.0.1:8000/api/restaurants/2/
Authorization: Bearer {{token}}

### 5. Добавить ресторан
POST http://127.0.0.1:8000/api/restaurants/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Doritos",
  "address": "124 Main St"
}

### 6. Обновить ресторан
PUT http://127.0.0.1:8000/api/restaurants/1/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "AmigoAmogus Updated",
  "address": "456 New St"
}

### 7. Удалить ресторан
DELETE http://127.0.0.1:8000/api/restaurants/1/
Authorization: Bearer {{token}}


### 8. Блюдо по ID
GET http://127.0.0.1:8000/api/dishes/1/
Authorization: Bearer {{token}}

### 9. Добавить блюдо
POST http://127.0.0.1:8000/api/dishes/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Amogunachos",
  "price": 125.00,
  "restaurant": 1
}

### 10. Обновить блюдо
PUT http://127.0.0.1:8000/api/dishes/1/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Amogunachos XXL",
  "price": 150.00
}

### 11. Удалить блюдо
DELETE http://127.0.0.1:8000/api/dishes/1/
Authorization: Bearer {{token}}

### 12. Получить корзину
GET http://127.0.0.1:8000/api/cart/
Authorization: Bearer {{token}}

### 13. Добавить блюдо в корзину
POST http://127.0.0.1:8000/api/cart/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "items": [
    {"dish": 1, "quantity": 2},
    {"dish": 2, "quantity": 1}
  ]
}

### 14. Обновить количество в корзине
PUT http://127.0.0.1:8000/api/cart/7/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "dish":1,
  "quantity": 20
}

### 15. Удалить блюдо из корзины
DELETE http://127.0.0.1:8000/api/cart/1/
Authorization: Bearer {{token}}

### 16. Создать заказ
POST http://127.0.0.1:8000/api/orders/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "cart_item_ids": [6, 7]
}

### 17. Заказ по ID
GET http://127.0.0.1:8000/api/orders/1/
Authorization: Bearer {{token}}

### 18. Список заказов пользователя
GET http://127.0.0.1:8000/api/orders/
Authorization: Bearer {{token}}

### 19. Изменить статус заказа
PUT http://127.0.0.1:8000/api/orders/1/status/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "status": "COMPLETED"
}

### 20. Получить профиль пользователя
GET http://127.0.0.1:8000/api/auth/profile/
Authorization: Bearer {{token}}

### 21. Обновить профиль пользователя
PUT http://127.0.0.1:8000/api/auth/profile/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "email": "newemail@example.com",
  "first_name": "Test",
  "last_name": "User"

}
