@host = http://127.0.0.1:8000
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzMTg5NDI3LCJpYXQiOjE3NjMxODkxMjcsImp0aSI6IjU2NGQ2MTZiMTRhNTQzMzJhYTVlNzQxZWVhODg4N2JmIiwidXNlcl9pZCI6IjMifQ.R79xb6eutrYEySPrIWbTDHt2sO-r52qGp901OxVySjk
GET {{host}}/api/auth/profile/
Authorization: Bearer {{token}}
Content-Type: application/json

### Регистрация нового пользователя тестового 1
POST http://127.0.0.1:8000/api/auth/register/
Content-Type: application/json

{
  "username": "testuser",
  "email": "test@example.com",
  "password": "password123"
}

### Регистрация нового пользователя тестового 1
POST http://127.0.0.1:8000/api/auth/register/
Content-Type: application/json

{
  "username": "testuser2",
  "email": "test2@example.com",
  "password": "password123"
}
### Обновление профиля
PUT http://127.0.0.1:8000/api/auth/profile/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "testuser2",
  "first_name": "Ivan",
  "last_name": "Petrov",
  "email": "ivan.petrov@example.com"
}
### Логин пользователя тестового 1
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
  "username": "testuser2",
  "password": "password123"
}

### Логин админа
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
  "username": "vmadmin",
  "password": "12345"
}

### Логин пользователя тестового 1
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123"
}

### Получить корзину текущего пользователя
GET http://127.0.0.1:8000/api/cart/
Authorization: Bearer {{token}}

### Получить профиль
GET {{host}}/api/auth/profile/
Authorization: Bearer {{token}}
Content-Type: application/json

### Добавить блюдо в корзину
POST http://127.0.0.1:8000/api/cart/
Authorization: Bearer {{token}}
Content-Type: application/json

[
  {"dish": 1, "quantity": 2},
  {"dish": 2, "quantity": 1}
]

### Создать заказ
POST http://127.0.0.1:8000/api/orders/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "cart_item_ids": [6]
}

###изменить статус
PUT http://127.0.0.1:8000/api/orders/1/status/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "status": "COMPLETED"
}